### ISSUE TITLE
Implement Scroll Animation App

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/Scroll-Animation#1]
https://50projects50days.com/projects/scroll-animation/

**Comment by arezooamiri** [comment]
Hi Farshad 
I  am facing a challenge in my latest commit ,I made changes to my code but  there is an issue where the scroll back box does not get removed, could you please review my code and help me with this ?

**Comment by FarshadJanmohammadi** [comment]
Hi Arezeou
I review this repository, and try to handle by second solution,but don't achive currect result.
just add initial view  box based on height screen.
previos solution is fine

**Comment by arezooamiri** [comment]
Thanks for your response ,but I really want do this with another solution ,It is fine

**Comment by arezooamiri** [comment]
Thanks for your response.
